export default [
  {
    id: "Showreel2021",
    name: {
      ko: "showreel",
      en: "showreel",
      jp: "",
      cn: "",
    },
    company: {
      ko: "2021 Looc Showreel",
      en: "2021 Looc Showreel",
      jp: "",
      cn: "",
    },
    type: "SHOWREEL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/661908910",
  },

  {
    id: "고요의 바다",
    name: {
      ko: "Opening Title | 고요의 바다",
      en: "Opening Title | Sabotage City",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Opening Title | 고요의 바다",
      en: "Opening Title | The serene sea",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/661081833",
  },
  {
    id: "공작도시",
    name: {
      ko: "Opening Title | 공작도시",
      en: "Opening Title | Sabotage City",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Opening Title | 공작도시",
      en: "Opening Title | Sabotage City",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/655256972",
  },
  {
    id: "DIGILOCA",
    name: {
      ko: "DIGILOCA | 티저",
      en: "DIGILOCA | Teaser",
      jp: "",
      cn: "",
    },
    company: {
      ko: "DIGILOCA | 티저",
      en: "DIGILOCA | Teaser",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/655258427",
  },
  {
    id: "코나카드 ",
    name: {
      ko: "코나 럭키카드 | 코나캐시떡상카드편",
      en: "Kona Lucky Card",
      jp: "",
      cn: "",
    },
    company: {
      ko: "코나 럭키카드 | 코나캐시떡상카드편",
      en: "Kona Lucky Card",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/653595553",
  },
  {
    id: "리브 넥스트",
    name: {
      ko: "KB | 리브 넥스트",
      en: "KB | Liiv Next",
      jp: "",
      cn: "",
    },
    company: {
      ko: "KB | 리브 넥스트",
      en: "KB | Liiv Next",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/653576214",
  },
  {
    id: "로카머니",
    name: {
      ko: "로카머니 | LOCAMONEY",
      en: "로카머니 | LOCAMONEY",
      jp: "",
      cn: "",
    },
    company: {
      ko: "로카머니 | LOCAMONEY",
      en: "로카머니 | LOCAMONEY",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/653600207",
  },
  // {
  //   id: "삼성 로고플레이 환경의달 편",
  //   name: {
  //     ko: "삼성 로고플레이 | 환경의달 편",
  //     en: "Samsung Logo Play | The month of the environment Compilation",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "삼성 로고플레이 | 환경의달 편",
  //     en: "Samsung Logo Play | The month of the environment Compilation",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "COMMERCIAL",
  //   mainImg: "",
  //   videoNew: "https://player.vimeo.com/video/653606982",
  // },
  // {
  //   id: "삼성 로고플레이 썸머(보트) 편",
  //   name: {
  //     ko: "삼성 로고플레이 | 썸머(보트) 편",
  //     en: "Samsung Logo Play | Summer(Boat) Compilation",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "삼성 로고플레이 | 썸머(보트) 편",
  //     en: "Samsung Logo Play | Summer(Boat) Compilation",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "COMMERCIAL",
  //   mainImg: "",
  //   videoNew: "https://player.vimeo.com/video/653608292",
  // },
  // {
  //   id: "삼성 로고플레이 썸머(파라솔) 편",
  //   name: {
  //     ko: "삼성 로고플레이 | 썸머(파라솔) 편",
  //     en: "Samsung Logo Play | Summer(Parasol) Compilation",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "삼성 로고플레이 | 썸머(파라솔) 편",
  //     en: "Samsung Logo Play | Summer(Parasol) Compilation",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "COMMERCIAL",
  //   mainImg: "",
  //   videoNew: "https://player.vimeo.com/video/653608706",
  // },
  // {
  //   id: "삼성 로고플레이 썸머(플라밍고) 편",
  //   name: {
  //     ko: "삼성 로고플레이 | 썸머(플라밍고) 편",
  //     en: "Samsung Logo Play | Summer(Flamingo) Compilation",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "삼성 로고플레이 | 썸머(플라밍고) 편",
  //     en: "Samsung Logo Play | Summer(Flamingo) Compilation",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "COMMERCIAL",
  //   mainImg: "",
  //   videoNew: "https://player.vimeo.com/video/653609058",
  // },
  // {
  //   id: "삼성 로고플레이 국제 손씻기의 날편",
  //   name: {
  //     ko: "삼성 로고플레이 | 국제 손씻기의 날편",
  //     en: "Samsung Logo Play ",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "삼성 로고플레이 | 국제 손씻기의 날편",
  //     en: "Samsung Logo Play ",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "COMMERCIAL",
  //   mainImg: "",
  //   videoNew: "https://player.vimeo.com/video/653609346",
  // },

  // {
  //   id: "삼성 로고플레이 기념편",
  //   name: {
  //     ko: "삼성 로고플레이 | 52주년 기념편",
  //     en: "Samsung Logo Play | 52nd anniversary. Commemoration Compilation",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "삼성 로고플레이 | 52주년 기념편",
  //     en: "Samsung Logo Play | 52nd anniversary. Commemoration Compilation",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "COMMERCIAL",
  //   mainImg: "",
  //   videoNew: "https://player.vimeo.com/video/653609581",
  // },
  // {
  //   id: "현대카드IRON",
  //   name: {
  //     ko: "현대카드 | IRON & WOOD",
  //     en: "Hyundai Card | IRON & WOOD",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "현대카드 | IRON & WOOD",
  //     en: "Hyundai Card | IRON & WOOD",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "COMMERCIAL",
  //   mainImg: "",
  //   videoNew: "https://player.vimeo.com/video/575702754",
  // },

  {
    id: "KLOUD",
    name: {
      ko: "KLOUD | 클라우드 X BTS",
      en: "KLOUD | KLOUD X BTS",
      jp: "",
      cn: "",
    },
    company: {
      ko: "KLOUD | 클라우드 X BTS",
      en: "KLOUD | KLOUD X BTS",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/575704729",
  },
  {
    id: "신한라이프",
    name: {
      ko: "신한라이프 | Brand ID",
      en: "Shinhan Life. | Brand ID",
      jp: "",
      cn: "",
    },
    company: {
      ko: "신한라이프 | Brand ID",
      en: "Shinhan Life. | Brand ID",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/575703806",
  },
  {
    id: "제주맥주",
    name: {
      ko: "제주맥주 | DIVE INTO DIVERSITY",
      en: "Jeju Beer | DIVE INTO DIVERSITY",
      jp: "",
      cn: "",
    },
    company: {
      ko: "제주맥주 | DIVE INTO DIVERSITY",
      en: "Jeju Beer | DIVE INTO DIVERSITY",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/585705906",
  },
  {
    id: "바디프렌드02",
    name: {
      ko: "바디프렌드 | 페이커",
      en: "Samsung | Galaxy Watch BIA",
      jp: "",
      cn: "",
    },
    company: {
      ko: "바디프렌드 | 페이커",
      en: "Samsung | Galaxy Watch BIA",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/625408651",
  },
  {
    id: "삼성",
    name: {
      ko: "삼성 | 갤럭시 워치 BIA",
      en: "Samsung | Galaxy Watch BIA",
      jp: "",
      cn: "",
    },
    company: {
      ko: "삼성 | 갤럭시 워치 BIA",
      en: "Samsung | Galaxy Watch BIA",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/625375447",
  },
  {
    id: "엘지",
    name: {
      ko: "엘지 Oled | ECO MINDED",
      en: "LG Oled | ECO MINDED",
      jp: "",
      cn: "",
    },
    company: {
      ko: "엘지 Oled | ECO MINDED",
      en: "LG Oled | ECO MINDED",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/625375486",
  },
  {
    id: "엘지01",
    name: {
      ko: "엘지 Oled | EYE COMFORT",
      en: "LG Oled | EYE COMFORT",
      jp: "",
      cn: "",
    },
    company: {
      ko: "엘지 Oled | EYE COMFORT",
      en: "LG Oled | EYE COMFORT",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/625375544",
  },
  {
    id: "엘지02",
    name: {
      ko: "엘지 Oled | MISSION",
      en: "LG Oled | MISSION",
      jp: "",
      cn: "",
    },
    company: {
      ko: "엘지 Oled | MISSION",
      en: "LG Oled | MISSION",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/625375595",
  },
  {
    id: "바디프렌드",
    name: {
      ko: "바디프렌드 | 박세리",
      en: "BODYFRIEND | Se-ri Pak",
      jp: "",
      cn: "",
    },
    company: {
      ko: "바디프렌드 | 박세리",
      en: "BODYFRIEND | Se-ri Pak",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/625375642",
  },
  {
    id: "바디프렌드01",
    name: {
      ko: "바디프렌드 | 손흥민",
      en: "BODYFRIEND | Heung-min Son",
      jp: "",
      cn: "",
    },
    company: {
      ko: "바디프렌드 | 손흥민",
      en: "BODYFRIEND | Heung-min Son",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/625375699",
  },
  {
    id: "정관장",
    name: {
      ko: "정관장 | Everytime Global",
      en: "Cheong-Kwan-Jang | Everytime Global",
      jp: "",
      cn: "",
    },
    company: {
      ko: "정관장 | Everytime Global",
      en: "Cheong-Kwan-Jang | Everytime Global",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/624416801",
  },
  {
    id: "CJ_ON",
    name: {
      ko: "CJ온스타일 | 상품전문가 편",
      en: "CJ OnStyle  | Product expert episode.",
      jp: "",
      cn: "",
    },
    company: {
      ko: "CJ온스타일 | 상품전문가 편",
      en: "CJ OnStyle  | Product expert episode.",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/624411230",
  },
  {
    id: "CJ_ON-LIVE",
    name: {
      ko: "CJ온스타일 | 라이브 편",
      en: "CJ OnStyle  | Live episode.",
      jp: "",
      cn: "",
    },
    company: {
      ko: "CJ온스타일 | 라이브 편",
      en: "CJ OnStyle  | Live episode.",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/624411182",
  },
  {
    id: "oera",
    name: {
      ko: "오에라 | 브랜드 스토리",
      en: "Oera | Brand Story",
      jp: "",
      cn: "",
    },
    company: {
      ko: "오에라 | 브랜드 스토리",
      en: "Oera | Brand Story",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/624408838",
  },
  {
    id: "CM",
    name: {
      ko: "commercial",
      en: "commercial",
      jp: "",
      cn: "",
    },
    company: {
      ko: "에블린 마스크 | 스타일링 컬러 마스크",
      en: "Evelyn Mask | Styling color mask",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/591373850",
  },
  {
    id: "머스트잇",
    name: {
      ko: "머스트잇",
      en: "Must it",
      jp: "",
      cn: "",
    },
    company: {
      ko: "머스트잇",
      en: "Must it",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/591366301",
  },

  // 10.28 Update 부분
  {
    id: "alien",
    name: {
      ko: "ALIEN",
      en: "ALIEN",
      jp: "",
      cn: "",
    },
    company: {
      ko: "LEE SUHYUN - ‘ALIEN’",
      en: "LEE SUHYUN - ‘ALIEN’",
      jp: "",
      cn: "",
    },
    type: "MV",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/472901907",
  },
  {
    id: "vimeo03",
    name: {
      ko: "동행세일 | 2021 대한민국 동행세일",
      en: "Accompanying Sale | 2021 Korea accompanying sale",
      jp: "",
      cn: "",
    },
    company: {
      ko: "동행세일 | 2021 대한민국 동행세일",
      en: "Accompanying Sale | 2021 Korea accompanying sale",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/575703072",
  },
  {
    id: "vimeo02",
    name: {
      ko: "Naver | 네이버 쇼핑라이브 1주년",
      en: "Naver | Shopping Live 1st Anniversary",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Naver | 네이버 쇼핑라이브 1주년",
      en: "Naver | Shopping Live 1st Anniversary",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/575706724",
  },
  {
    id: "현대카드",
    name: {
      ko: "현대카드 | the Pink",
      en: "Hyundai Card | the Pink",
      jp: "",
      cn: "",
    },
    company: {
      ko: "현대카드 | the Pink",
      en: "Hyundai Card | the Pink",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/575703734",
  },
  {
    id: "vimeo01",
    name: {
      ko: "현대카드 | the Pink",
      en: "Hyundai Card | the Pink",
      jp: "",
      cn: "",
    },
    company: {
      ko: "현대카드 | the Pink",
      en: "Hyundai Card | the Pink",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/575703760",
  },
  {
    id: "Dragon_Roi",
    name: {
      ko: "Dragon_Roi",
      en: "Dragon_Roi",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Dragon_Roi",
      en: "Dragon_Roi",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/538567904",
  },

  {
    id: "ROCA_Money",
    name: {
      ko: "ROCA_Money",
      en: "ROCA_Money",
      jp: "",
      cn: "",
    },
    company: {
      ko: "ROCA_Money",
      en: "ROCA_Moneyr",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/538507405",
  },

  {
    id: "BESPOKE_directer",
    name: {
      ko: "BESPOKE_directer",
      en: "BESPOKE_directer",
      jp: "",
      cn: "",
    },
    company: {
      ko: "BESPOKE_directer",
      en: "BESPOKE_directer",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/527082917",
  },

  {
    id: "Icarus_Teaser",
    name: {
      ko: "ICARUS | Teaser",
      en: "ICARUS | Teaser",
      jp: "",
      cn: "",
    },
    company: {
      ko: "ICARUS | Teaser",
      en: "ICARUS | Teaser",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/515568312",
  },

  {
    id: "Hyundaicard_Socar_Looc_ver",
    name: {
      ko: "Hyundaicard_Socar_Looc_ver",
      en: "Hyundaicard_Socar_Looc_ver",
      jp: "",
      cn: "",
    },
    company: {
      ko: "현대카드 | 쏘카 _ LOOC.ver",
      en: "Hyundaicard_Socar_Looc_ver",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/510526186",
  },

  {
    id: "kakao_emoticon",
    name: {
      ko: "Kakao | Emoticon Plus",
      en: "Kakao | Emoticon Plus",
      jp: "",
      cn: "",
    },
    company: {
      ko: "카카오 | 이모티콘 플러스",
      en: "Kakao | Emoticon Plus",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/506923070",
  },

  {
    id: "kia_mohave",
    name: {
      ko: "Kia_Mohave",
      en: "Kia_Mohave",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Kia Mohave | The matser | Dreams are young",
      en: "Kia Mohave | The matser | Dreams are young",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/506921408",
  },

  {
    id: "samsung_CES",
    name: {
      ko: "CES",
      en: "CES",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Samsung | CES 2021 Title",
      en: "Samsung | CES 2021 Title",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/499461535",
  },

  {
    id: "lg_logo",
    name: {
      ko: "LG",
      en: "LG",
      jp: "",
      cn: "",
    },
    company: {
      ko: "LG Logo Animation 15s",
      en: "LG Logo Animation 15s",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/499464405",
  },
  {
    id: "mx_boost",
    name: {
      ko: "현대카드",
      en: "Hyundai Card",
      jp: "",
      cn: "",
    },
    company: {
      ko: "현대카드 | MX Boost 30s",
      en: "Hyundai Card | MX Boost 30s",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/499461558",
  },
  {
    id: "hyundai_rima",
    name: {
      ko: "현대카드",
      en: "Hyundai Card",
      jp: "",
      cn: "",
    },
    company: {
      ko: "현대카드 | 현대카드 RIMA",
      en: "Hyundai Card | Hyundai Card RIMA",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/485340394",
  },
  {
    id: "melon_mma",
    name: {
      ko: "멜론",
      en: "Melon",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Melon | MMA",
      en: "Melon | MMA",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/485299555",
  },
  {
    id: "mc365",
    name: {
      ko: "365mc",
      en: "365mc",
      jp: "",
      cn: "",
    },
    company: {
      ko: "365mc | Brand Film Dir ver.",
      en: "365mc | Brand Film Dir ver.",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/485298725",
  },
  {
    id: "sulwhasoo",
    name: {
      ko: "설화수",
      en: "Sulwhasoo",
      jp: "",
      cn: "",
    },
    company: {
      ko: "설화수 | Sulwhasoo",
      en: "Sulwhasoo",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/484421372",
  },
  {
    id: "yongfilm",
    name: {
      ko: "Yongfilm",
      en: "Yongfilm",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Yongfilm | 리더필름 ‘Yongfilm’",
      en: "Yongfilm | 리더필름 ‘Yongfilm’",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/484420918",
  },
  {
    id: "naver_flower",
    name: {
      ko: "프로젝트 꽃",
      en: "Project flower",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Naver | 프로젝트 꽃 Interview teaser",
      en: "Naver | Project flower Interview teaser",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/484396961",
  },
  {
    id: "primera",
    name: {
      ko: "알파인 베리 워터리 크림",
      en: "Alpine Berry Watery Cream",
      jp: "",
      cn: "",
    },
    company: {
      ko: "프리메라 | 알파인 베리 워터리 크림",
      en: "Primera | Alpine Berry Watery Cream",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/472902036",
  },
  {
    id: "neulteq",
    name: {
      ko: "늘테크",
      en: "Neulteq",
      jp: "",
      cn: "",
    },
    company: {
      ko: "신한카드 늘테크",
      en: "Shinnan Card Neulteq",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/472902017",
  },
  {
    id: "drumjunghwa",
    name: {
      ko: "lm Differen_엄정화",
      en: "lm Differen_umjunghwa",
      jp: "",
      cn: "",
    },
    company: {
      ko: "닥터디퍼런트 lm Differen_엄정화",
      en: "Dr.Differen lm Differen_umjunghwa",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/472902001",
  },
  {
    id: "drteaser",
    name: {
      ko: "lm Different_Teaser",
      en: "lm Different_Teaser",
      jp: "",
      cn: "",
    },
    company: {
      ko: "닥터디퍼런트 lm Different_Teaser",
      en: "Dr.Different lm Different_Teaser",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/472901982",
  },
  {
    id: "naverRetail",
    name: {
      ko: "Ratil_TVC_30s",
      en: "Ratil_TVC_30s",
      jp: "",
      cn: "",
    },
    company: {
      ko: "네이버 시리즈 Ratil_TVC_30s",
      en: "Naver series Ratil_TVC_30s",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/472901975",
  },
  {
    id: "naverRanamoonTvc",
    name: {
      ko: "Ranamoon_TVC_30s",
      en: "Ranamoon_TVC_30s",
      jp: "",
      cn: "",
    },
    company: {
      ko: "네이버 시리즈 Ranamoon_TVC_30s",
      en: "Naver series Ranamoon_TVC_30s",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/472901937",
  },
  {
    id: "naverRanamoonDigital",
    name: {
      ko: "Ranamoon_Digital",
      en: "Ranamoon_Digital",
      jp: "",
      cn: "",
    },
    company: {
      ko: "네이버 시리즈 Ranamoon_Digital",
      en: "Naver series Ranamoon_Digital",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/472901917",
  },
  {
    id: "JMsolutionGlow",
    name: {
      ko: "글로우 필 스파크림",
      en: "Glow fill SPA Cream",
      jp: "",
      cn: "",
    },
    company: {
      ko: "JMsolution | 글로우 필 스파크림",
      en: "JMsolution | Glow fill SPA Cream",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/472901878",
  },
  {
    id: "colormatching",
    name: {
      ko: "컬러 매칭 콜라보레이션",
      en: "Color matching collaboration",
      jp: "",
      cn: "",
    },
    company: {
      ko: "갤럭시 노트20 컬러 매칭 콜라보레이션",
      en: "GLAXY NOTE20 Color matching collaboration",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/472901856",
  },
  {
    id: "SamsungInduction",
    name: {
      ko: "All induction_Digital",
      en: "All induction_Digital",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Samsung All induction_Digital",
      en: "Samsung All induction_Digital",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/472901855",
  },
  {
    id: "maumhangul",
    name: {
      ko: "마음한줄",
      en: "A line of heart",
      jp: "",
      cn: "",
    },
    company: {
      ko: "갤럭시 노트20 마음한줄",
      en: "GLAXY NOTE20 A line of heart",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/472901825",
  },
  {
    id: "skmagic",
    name: {
      ko: "스스로 직수정수기",
      en: "water purifier",
      jp: "",
      cn: "",
    },
    company: {
      ko: "SK매직 스스로 직수정수기",
      en: "SK Magic water purifier",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/472901821",
  },
  {
    id: "iopeexpert",
    name: {
      ko: "레티놀 엑스퍼트",
      en: "Retinol Expert",
      jp: "",
      cn: "",
    },
    company: {
      ko: "IOPE 레티놀 엑스퍼트 01%",
      en: "IOPE Retinol Expert 01%",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/472901797",
  },
  {
    id: "cliokill",
    name: {
      ko: "킬커버 픽서 쿠션",
      en: "Kill Cover",
      jp: "",
      cn: "",
    },
    company: {
      ko: "클리오 킬커버 픽서 쿠션",
      en: "CLIO | Kill Cover Fixer Cushion",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/472901780",
  },
  {
    id: "ktskylife",
    name: {
      ko: "스카이라이프",
      en: "Skylife",
      jp: "",
      cn: "",
    },
    company: {
      ko: "KT 스카이라이프",
      en: "KT Skylife",
      jp: "",
      cn: "",
    },
    type: "MOTION",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/472901762",
  },
  {
    id: "bibigoPremier",
    name: {
      ko: "프리미엄죽",
      en: "Premium",
      jp: "",
      cn: "",
    },
    company: {
      ko: "비비고 프리미엄죽 | 죽이 맞다",
      en: "BIBIGO Premium",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/472901749",
  },
  {
    id: "bibigoBulnak",
    name: {
      ko: "불낙죽편",
      en: "불낙죽 episode",
      jp: "",
      cn: "",
    },
    company: {
      ko: "비비고 프리미엄죽 | 불낙죽편",
      en: "BIBIGO | 불낙죽 episode’",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/472901748",
  },
  // 08.26 Update 부분
  {
    id: "double_decker",
    name: {
      ko: "쌍갑포차",
      en: "A Double Decker",
      jp: "",
      cn: "",
    },
    company: {
      ko: "쌍갑포차 오프닝 타이틀",
      en: "A Double Decker Opening title",
      jp: "",
      cn: "",
    },
    type: "OPENING TITLE",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/451750444",
  },
  {
    id: "My Country",
    name: {
      ko: "OT",
      en: "OT",
      jp: "",
      cn: "",
    },
    company: {
      ko: "나의 나라",
      en: "My Country",
      jp: "",
      cn: "",
    },
    type: "OPENING TITLE",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/451757003",
  },
  // 20.08.03 Update 부분
  {
    id: "식빵 언니",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "식빵 언니 #김연경 선수 아이돌 데뷔 링티",
      en: "Bread sister #Kim Yeon-kyung's idol debut ringtee",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444152205",
  },
  {
    id: "클라우드 생 드래프트",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "클라우드 생 드래프트(feat.박서준)",
      en: "Cloud draft (feat.park seo joon)",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444152220",
  },
  {
    id: "bibigo",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "비비고 | 프리미엄 국물요리",
      en: "Bibigo | Premium Soup",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444151926",
  },
  {
    id: "dokgo",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "배달의 민족 | 독고배달이",
      en: "BAEMIN | Dokgo",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444152045",
  },
  {
    id: "Nyang",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "배달의민족 | 냥이배달이",
      en: "BAEMIN | Nyang",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444152019",
  },
  {
    id: "my long",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "배달의민족 | 마이배달이",
      en: "BAEMIN | My Baedal",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444151969",
  },
  {
    id: "Do you know Samsumg membership02",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "삼성전자 멤버쉽 | Do you know 2",
      en: "Do you khow Samsung Electronics Membership #2",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444127648",
  },
  {
    id: "Do you know Samsumg membership01",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "삼성전자 멤버쉽 | Do you know 1",
      en: "Do you khow Samsung Electronics Membership #1",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444125083",
  },

  {
    id: "lg woman",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "LG | TONEFREE 여자편",
      en: "LG | TONEFREE WOMAN",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444152006",
  },
  {
    id: "lg man",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "LG | TONEFREE 남자편",
      en: "LG | TONEFREE MAN",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444151996",
  },

  {
    id: "kb teaser",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "2020 KB | 티저",
      en: "2020 KB | teaser",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444152058",
  },
  {
    id: "30 second",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "현대카드 | People",
      en: "HyundaiCard | People",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444151945",
  },
  {
    id: "together",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "대한민국 동행세일",
      en: "Together",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444152190",
  },
  {
    id: "brol",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "브롤스타즈 | 블랙핑크",
      en: "Brolstars | BLACKPINK",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444152088",
  },
  {
    id: "sleep",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "삼성 Health | Sleep",
      en: "Samsung Health | Sleep",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444152161",
  },
  {
    id: "meditation",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "삼성 Health | Meditation",
      en: "Samsung Health | Meditation",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444152150",
  },
  {
    id: "hometraining",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "삼성 Health | Hometraining",
      en: "Samsung Health | Hometraining",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444152136",
  },
  {
    id: "bixby",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "빅스비 | bixby",
      en: "Bixby",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444152116",
  },
  {
    id: "Take off 30",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "현대카드 + 대한항공 | Take off",
      en: "Hyundai Card + Korean Air | Take off",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444152174",
  },
  {
    id: "history",
    name: {
      ko: "COMMERCIAL",
      en: "COMMERCIAL",
      jp: "",
      cn: "",
    },
    company: {
      ko: "현대카드 + 대한항공 | History",
      en: "Hyundai Card + Korean Air | HISTORY",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/444152125",
  },

  //////// 기존

  {
    id: "15초 단편버전_A",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "15초 단편버전A",
      en: "15-second short versionA",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/427261694",
  },
  {
    id: "2018_Kingdom_Title",
    name: {
      ko: "OT",
      en: "OT",
      jp: "",
      cn: "",
    },
    company: {
      ko: "2018 Kingdom Title",
      en: "2018 Kingdom Title",
      jp: "",
      cn: "",
    },
    type: "OPENING TITLE",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/427261878",
  },
  {
    id: "2019_LYN_TVC_direct_Full",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "2019 LYN TVC direct Full",
      en: "2019 LYN TVC direct Full",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/427271870",
  },
  {
    id: "2019_shinsegae_45A",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "2019 shinsegae 45A",
      en: "2019 shinsegae 45A",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/427273260",
  },
  {
    id: "2019_라이나_요리매연",
    name: {
      ko: "Motion",
      en: "Motion",
      jp: "",
      cn: "",
    },
    company: {
      ko: "2019 라이나 요리매연",
      en: "2019 lina cooking Smoke",
      jp: "",
      cn: "",
    },
    type: "MOTION",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/427273729",
  },
  {
    id: "anssil_Teaser_IFdesign",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "anssil Teaser IFdesign",
      en: "anssil Teaser IFdesign",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/427274640",
  },
  {
    id: "oilbank_2460_936",
    name: {
      ko: "Motion",
      en: "Motion",
      jp: "",
      cn: "",
    },
    company: {
      ko: "oilbank 2460 936",
      en: "oilbank 2460 936",
      jp: "",
      cn: "",
    },
    type: "MOTION",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/427275163",
  },
  {
    id: "CLIO 프리즘 에어 아이 팔레트",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "CLIO 프리즘 에어 아이 팔레트",
      en: "CLIO Prism Air Eye Palette",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/427275283",
  },
  {
    id: "2020_JM_Solution_30A",
    name: {
      ko: "Motion",
      en: "Motion",
      jp: "",
      cn: "",
    },
    company: {
      ko: "2020 JM Solution 30A",
      en: "2020 JM Solution 30A",
      jp: "",
      cn: "",
    },
    type: "MOTION",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/427275457",
  },
  {
    id: "2020_Samsung_Grande",
    name: {
      ko: "Motion",
      en: "Motion",
      jp: "",
      cn: "",
    },
    company: {
      ko: "2020 Samsung Grande",
      en: "2020 Samsung Grande",
      jp: "",
      cn: "",
    },
    type: "MOTION",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/427275829",
  },
  {
    id: "2020_JTBC_TV 방송용 A_가치편",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "2020 JTBC TV 방송용 A 가치편",
      en: "2020 JTBC TV Broadcasting A Value Edition",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/427277692",
  },
  {
    id: "2020_JTBC_TV 방송용 B_정신편",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "2020 JTBC TV 방송용 B 정신편",
      en: "2020 JTBC TV Broadcast B Mental",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/427278421",
  },
  {
    id: "2020_JTBC_TV 방송용 C_자세편",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "2020 JTBC TV 방송용 C 자세편",
      en: "2020 JBC TV Broadcasting C Posture",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/427279361",
  },
  {
    id: "Samsungcard_All",
    name: {
      ko: "Motion",
      en: "Motion",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Samsungcard All",
      en: "Samsungcard All",
      jp: "",
      cn: "",
    },
    type: "MOTION",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/427280045",
  },
  {
    id: "Domino_Pizza",
    name: {
      ko: "Motion",
      en: "Motion",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Domino Pizza",
      en: "Domino Pizza",
      jp: "",
      cn: "",
    },
    type: "MOTION",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/427281792",
  },
  {
    id: "2020_Galaxy_A_Quantum",
    name: {
      ko: "Motion",
      en: "Motion",
      jp: "",
      cn: "",
    },
    company: {
      ko: "2020 Galaxy A Quantum",
      en: "2020 Galaxy A Quantum",
      jp: "",
      cn: "",
    },
    type: "MOTION",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/427282235",
  },
  {
    id: "2020_Galaxy_A_Quantum_2",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "2020 Galaxy A Quantum 2",
      en: "2020 Galaxy A Quantum 2",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/427282160",
  },
  {
    id: "GD_untitle",
    name: {
      ko: "MV",
      en: "MV",
      jp: "",
      cn: "",
    },
    company: {
      ko: "GD 무제",
      en: "GD Untitle",
      jp: "",
      cn: "",
    },
    type: "MV",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/428444098",
  },
  {
    id: "LEE_HI_NO-ONE",
    name: {
      ko: "MV",
      en: "MV",
      jp: "",
      cn: "",
    },
    company: {
      ko: "LEE HI-NO ONE",
      en: "LEE HI-NO ONE",
      jp: "",
      cn: "",
    },
    type: "MV",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/428444202",
  },
  {
    id: "你好吗我很好谢谢你呢",
    name: {
      ko: "MV",
      en: "MV",
      jp: "",
      cn: "",
    },
    company: {
      ko: "你好吗我很好谢谢你呢-Chris Lee",
      en: "你好吗我很好谢谢你呢-Chris Lee",
      jp: "",
      cn: "",
    },
    type: "MV",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/428444739",
  },
  {
    id: "流行_TREND",
    name: {
      ko: "MV",
      en: "MV",
      jp: "",
      cn: "",
    },
    company: {
      ko: "流行 TREND",
      en: "流行 TREND",
      jp: "",
      cn: "",
    },
    type: "MV",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/428445382",
  },
  {
    id: "Park_Ji_Yoon_Beep",
    name: {
      ko: "MV",
      en: "MV",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Park Ji Yoon-Beep",
      en: "Park Ji Yoon-Beep",
      jp: "",
      cn: "",
    },
    type: "MV",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/428445830",
  },
  {
    id: "PERFECT",
    name: {
      ko: "MV",
      en: "MV",
      jp: "",
      cn: "",
    },
    company: {
      ko: "PERFECT",
      en: "PERFECT",
      jp: "",
      cn: "",
    },
    type: "MV",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/428446077",
  },
  {
    id: "yoon_jong_sin",
    name: {
      ko: "MV",
      en: "MV",
      jp: "",
      cn: "",
    },
    company: {
      ko: "윤종신 - 그대 여전히 멋있는 사람",
      en: "Yoon Jong Shin - You are still cool",
      jp: "",
      cn: "",
    },
    type: "MV",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/428446569",
  },
  {
    id: "lexus_taeyang",
    name: {
      ko: "MV",
      en: "MV",
      jp: "",
      cn: "",
    },
    company: {
      ko: "렉서스 X 태양 - SO Good",
      en: "lexus X taeyang - So Good",
      jp: "",
      cn: "",
    },
    type: "MV",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/428446667",
  },
  {
    id: "park_ji_yoon_Yoo_hoo",
    name: {
      ko: "MV",
      en: "MV",
      jp: "",
      cn: "",
    },
    company: {
      ko: "박지윤 - Yoo Hoo",
      en: "Park Ji Yoon - Yoo Hoo",
      jp: "",
      cn: "",
    },
    type: "MV",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/428446883",
  },
  {
    id: "Priest title",
    name: {
      ko: "OT",
      en: "OT",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Priest Title",
      en: "Priest Title",
      jp: "",
      cn: "",
    },
    type: "OPENING TITLE",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/395442161",
  },
  {
    id: "Onmyoji - New SP Shikigami Demoniac Shuten Doji",
    name: {
      ko: "Motion",
      en: "Motion",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Onmyoji - New SP Shikigami Demoniac Shuten Doji",
      en: "Onmyoji - New SP Shikigami Demoniac Shuten Doji",
      jp: "",
      cn: "",
    },
    type: "MOTION",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/395442101",
  },
  {
    id: "Samsung intro no frame",
    name: {
      ko: "Motion",
      en: "Motion",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Samsung Intro No Frame",
      en: "Samsung Intro No Frame",
      jp: "",
      cn: "",
    },
    type: "MOTION",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/395442074",
  },
  {
    id: "LiivM Launching 30",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "LiivM Launching 30",
      en: "LiivM Launching 30",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/395442007",
  },
  {
    id: "[비맥스 메타정] 정신피로 편",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "[비맥스 메타정] 정신피로 편",
      en: "[비맥스 메타정] 정신피로 편",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/395441950",
  },
  {
    id: "Fomula-E with방탄소년단",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Fomula-E",
      en: "Fomula-E",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/395441914",
  },
  {
    id: "All New Galaxy A",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "All New Galaxy A",
      en: "All New Galaxy A",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/395441891",
  },
  {
    id: "New K5 Teaser",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "New K5 - 티져",
      en: "New K5 - Teaser",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389487146",
  },
  {
    id: "Samsung Galaxy Wallpaper Film",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "삼성 갤럭시 - Wallpaper film",
      en: "Samsung Galaxy Wallpaper film",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389487105",
  },
  {
    id: "Www Title",
    name: {
      ko: "OT",
      en: "OT",
      jp: "",
      cn: "",
    },
    company: {
      ko: "WWW - 타이틀 ",
      en: "WWW - Title ",
      jp: "",
      cn: "",
    },
    type: "OPENING TITLE",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389487074",
  },
  {
    id: "Samsung Block Chain",
    name: {
      ko: "Motion",
      en: "Motion",
      jp: "",
      cn: "",
    },
    company: {
      ko: "삼성 블록체인",
      en: "Samsung Blockchain",
      jp: "",
      cn: "",
    },
    type: "MOTION",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389486994",
  },
  {
    id: "Sk Holdings Jjack",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "SK Holdings - JJAK",
      en: "SK Holdings - JJAK",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389486969",
  },
  {
    id: "Sk Holdings Up",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "SK Holdings - UP",
      en: "SK Holdings - UP",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389486947",
  },
  {
    id: "Naver Series Prenup",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Naver Series - Prenup",
      en: "Naver Series - Prenup",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389486917",
  },
  {
    id: "Naver Series Goldenhour",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Naver Series - Goldenhour",
      en: "Naver Series - Goldenhour",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389486890",
  },
  {
    id: "Manyo",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Manyo",
      en: "Manyo",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389486847",
  },
  {
    id: "Lotte Chemical",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "롯데 케미칼",
      en: "Lotte Chemical",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389486822",
  },
  {
    id: "Hyundai Card Dive",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Hyundaicard DIVE",
      en: "Hyundaicard DIVE",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389486799",
  },
  {
    id: "Chapi",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Chapi",
      en: "Chapi",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389486757",
  },
  {
    id: "Soofee",
    name: {
      ko: "Motion",
      en: "Motion",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Soofe'e",
      en: "Soofe'e",
      jp: "",
      cn: "",
    },
    type: "MOTION",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389486731",
  },
  {
    id: "Lineage 2m Bi",
    name: {
      ko: "Motion",
      en: "Motion",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Lineage2 M BI",
      en: "Lineage2 M BI",
      jp: "",
      cn: "",
    },
    type: "MOTION",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389486706",
  },
  {
    id: "Blade And Soul",
    name: {
      ko: "TVC",
      en: "TVC",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Blade & Soul",
      en: "Blade & Soul",
      jp: "",
      cn: "",
    },
    type: "COMMERCIAL",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389486676",
  },
  {
    id: "Beauty Inside Ending Title",
    name: {
      ko: "OT",
      en: "OT",
      jp: "",
      cn: "",
    },
    company: {
      ko: "뷰티인사이드 - 엔딩 타이틀",
      en: "Beauty Inside Ending Title",
      jp: "",
      cn: "",
    },
    type: "OPENING TITLE",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389486653",
  },
  {
    id: "Snowpiercer Title",
    name: {
      ko: "OT",
      en: "OT",
      jp: "",
      cn: "",
    },
    company: {
      ko: "설국열차 - 타이틀",
      en: "Snowpiercer-Title",
      jp: "",
      cn: "",
    },
    type: "OPENING TITLE",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389486623",
  },
  {
    id: "Lost Kingdom",
    name: {
      ko: "Motion",
      en: "Motion",
      jp: "",
      cn: "",
    },
    company: {
      ko: "Lost Kingdom",
      en: "Lost Kingdom",
      jp: "",
      cn: "",
    },
    type: "Motion",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389486596",
  },
  {
    id: "Lg Optimus G",
    name: {
      ko: "Motion",
      en: "Motion",
      jp: "",
      cn: "",
    },
    company: {
      ko: "LG Optimus G",
      en: "LG Optimus G",
      jp: "",
      cn: "",
    },
    type: "MOTION",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389486550",
  },
  {
    id: "Cgv Elevator",
    name: {
      ko: "Motion",
      en: "Motion",
      jp: "",
      cn: "",
    },
    company: {
      ko: "CGV-ELEVATOR",
      en: "CGV-ELEVATOR",
      jp: "",
      cn: "",
    },
    type: "MOTION",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389486493",
  },
  {
    id: "All New Cgv",
    name: {
      ko: "Motion",
      en: "Motion",
      jp: "",
      cn: "",
    },
    company: {
      ko: "All NEW CGV",
      en: "All NEW CGV",
      jp: "",
      cn: "",
    },
    type: "MOTION",
    mainImg: "",
    videoNew: "https://player.vimeo.com/video/389486429",
  },
  //ArtWork
  // {
  //   id: "alienArt",
  //   name: {
  //     ko: "Looc",
  //     en: "Looc",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "Alien - LEE SUHYUN | Project Guide",
  //     en: "Alien - LEE SUHYUN | Project Guide",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "ARTWORK",
  //   mainImg: ailien,
  //   detailImg: alienDetail,
  //   videoNew: "https://player.vimeo.com/video/472901907",
  // },
  // {
  //   id: "bespokeArt",
  //   name: {
  //     ko: "Looc",
  //     en: "Looc",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "Bespoke | Project Guide",
  //     en: "Bespoke | Project Guide",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "ARTWORK",
  //   mainImg: bespoke2,
  //   detailImg: bespokeDetail,
  //   videoNew: "https://player.vimeo.com/video/527082917",
  // },
  // {
  //   id: "betterSamsung",
  //   name: {
  //     ko: "Samsung",
  //     en: "Samsung",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "Better Normal for All | Project Guide",
  //     en: "Better Normal for All | Project Guide",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "ARTWORK",
  //   mainImg: samsung,
  //   detailImg: samsungDetail,
  //   videoNew: "https://player.vimeo.com/video/499461535",
  // },
  // {
  //   id: "whatHappend",
  //   name: {
  //     ko: "Looc",
  //     en: "Looc",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "What Happened to 30's | Porject Guide",
  //     en: "What Happened to 30's | Porject Guide",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "ARTWORK",
  //   mainImg: whatHappend,
  //   detailImg: whatHappendDetail,
  // },
  // {
  //   id: "hyundaicard_art",
  //   name: {
  //     ko: "Hyundai Card",
  //     en: "Hyundai Card",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "Hyundaicard Rima | Porject Guide",
  //     en: "Hyundaicard Rima | Porject Guide",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "ARTWORK",
  //   mainImg: hyundai_art,
  //   detailImg: hyundai_artDetail,
  //   videoNew: "https://player.vimeo.com/video/485340394",
  // },
  // {
  //   id: "milkshake",
  //   name: {
  //     ko: "Play Looc",
  //     en: "Play Looc",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "Milke Shake | Project Guide",
  //     en: "Milke Shake | Project Guide",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "ARTWORK",
  //   mainImg: milkshake,
  //   detailImg: milkshakeDetail,
  // },
  // {
  //   id: "priest",
  //   name: {
  //     ko: "Priest",
  //     en: "Priest",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "Priest | Project Guide",
  //     en: "Priest | Project Guide",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "ARTWORK",
  //   mainImg: "",
  //   detailImg: priestDetail,
  //   videoNew: "https://player.vimeo.com/video/395442161",
  // },
  // {
  //   id: "skylifeArt",
  //   name: {
  //     ko: "KT Skylife",
  //     en: "KT Skylife",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "KT Skylife | Project Guide",
  //     en: "KT Skylife | Project Guide",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "ARTWORK",
  //   mainImg: "",
  //   detailImg: ktSkylifeDetail,
  //   videoNew: "https://player.vimeo.com/video/472901762",
  // },
  // {
  //   id: "darkCircle",
  //   name: {
  //     ko: "Dark Circle Pictures",
  //     en: "Dark Circle Pictures",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "Dark Circle Pictures | Project Guide",
  //     en: "Dark Circle Pictures | Project Guide",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "ARTWORK",
  //   mainImg: dark,
  //   detailImg: darkDetail,
  // },
  // {
  //   id: "daisy",
  //   name: {
  //     ko: "DAISY",
  //     en: "DAISY",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "DAISY - Lost Rabbit | Project Guide",
  //     en: "DAISY - Lost Rabbit | Project Guide",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "ARTWORK",
  //   mainImg: [daisy],
  // },
  // {
  //   id: "timing",
  //   name: {
  //     ko: "컨셉큐브",
  //     en: "Concept Cube",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "Timing Alice | Project Guide",
  //     en: "Timing Alice | Project Guide",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "ARTWORK",
  //   mainImg: timing,
  //   detailImg: timingDetail,
  // },
  // {
  //   id: "timingDark",
  //   name: {
  //     ko: "컨셉큐브",
  //     en: "Concept Cube",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "Timing Alice | Project Guide",
  //     en: "Timing Alice | Project Guide",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "ARTWORK",
  //   mainImg: timingDark,
  //   detailImg: timingDarkDetail,
  // },
  // {
  //   id: "lyn",
  //   name: {
  //     ko: "LYN",
  //     en: "LYN",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "Lyn - The Lightbringer | Project Guide",
  //     en: "Lyn - The Lightbringer | Project Guide",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "ARTWORK",
  //   mainImg: "",
  //   detailImg: lynDetail,
  //   videoNew: "https://player.vimeo.com/video/330937494",
  // },
  // {
  //   id: "victor",
  //   name: {
  //     ko: "Looc",
  //     en: "Looc",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "Victor - 비극의 탄생 | Project Guide",
  //     en: "Victor | Project Guide",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "ARTWORK",
  //   mainImg: victor,
  //   detailImg: victorDetail,
  // },
  // {
  //   id: "Showreel",
  //   name: {
  //     ko: "showreel",
  //     en: "showreel",
  //     jp: "",
  //     cn: "",
  //   },
  //   company: {
  //     ko: "2020 Looc Showreel",
  //     en: "2020 Looc Showreel",
  //     jp: "",
  //     cn: "",
  //   },
  //   type: "SHOWREEL",
  //   mainImg: "",
  //   videoNew: "https://player.vimeo.com/video/425415801",
  // },
];
